import { Player } from './CM0102Parser';

export const mockPlayerData: Partial<Player>[] = [
  {
    id: 1,
    firstName: 'Maxim',
    lastName: 'Tsigalko',
    commonName: 'Maxim Tsigalko',
    age: 18,
    clubName: 'Dinamo Minsk',
    nationalityName: 'Belarus',
    currentAbility: 160,
    potentialAbility: 200,
    value: 1200000,
    positions: { 'ST': 20, 'FW': 20 },
    attributes: {
      finishing: 20,
      acceleration: 19,
      pace: 18,
      determination: 20,
      workRate: 15,
      stamina: 16,
      composure: 18,
      offTheBall: 20,
      technique: 15,
      dribbling: 14,
      heading: 17
    },
  },
  {
    id: 2,
    firstName: 'Tonton',
    lastName: 'Zola Moukoko',
    commonName: 'Tonton Zola Moukoko',
    age: 17,
    clubName: 'Derby County',
    nationalityName: 'Sweden',
    currentAbility: 140,
    potentialAbility: 195,
    value: 500000,
    positions: { 'AM': 20, 'C': 20 },
    attributes: {
      finishing: 15,
      acceleration: 18,
      pace: 17,
      determination: 18,
      workRate: 14,
      stamina: 15,
      composure: 16,
      offTheBall: 18,
      technique: 19,
      dribbling: 19,
      heading: 10
    },
  },
  {
    id: 3,
    firstName: 'Cherno',
    lastName: 'Samba',
    commonName: 'Cherno Samba',
    age: 15,
    clubName: 'Millwall',
    nationalityName: 'England',
    currentAbility: 120,
    potentialAbility: 190,
    value: 300000,
    positions: { 'ST': 20 },
    attributes: {
      finishing: 18,
      acceleration: 20,
      pace: 20,
      determination: 17,
      workRate: 12,
      stamina: 14,
      composure: 15,
      offTheBall: 17,
      technique: 14,
      dribbling: 15,
      heading: 16
    },
  },
  {
    id: 4,
    firstName: 'Mark',
    lastName: 'Sigua',
    commonName: 'Mark Sigua',
    age: 16,
    clubName: 'Kutaisi',
    nationalityName: 'Georgia',
    currentAbility: 110,
    potentialAbility: 185,
    value: 150000,
    positions: { 'D': 20, 'C': 20 },
    attributes: {
      tackling: 18,
      marking: 17,
      positioning: 16,
      determination: 19,
      strength: 18,
      jumping: 17,
      pace: 15,
      acceleration: 14,
      workRate: 18,
      stamina: 17
    },
  },
  {
    id: 5,
    firstName: 'Kim',
    lastName: 'Källström',
    commonName: 'Kim Källström',
    age: 18,
    clubName: 'Häcken',
    nationalityName: 'Sweden',
    currentAbility: 135,
    potentialAbility: 180,
    value: 800000,
    positions: { 'M': 20, 'C': 20 },
    attributes: {
      passing: 18,
      creativity: 17,
      technique: 19,
      longShots: 20,
      freeKicks: 19,
      determination: 16,
      pace: 13,
      strength: 15,
      stamina: 16
    },
  },
  {
    id: 6,
    firstName: 'Taribo',
    lastName: 'West',
    commonName: 'Taribo West',
    age: 27,
    clubName: 'Free Agent',
    nationalityName: 'Nigeria',
    currentAbility: 155,
    potentialAbility: 165,
    value: 0,
    positions: { 'D': 20, 'LC': 20 },
    attributes: {
      tackling: 20,
      marking: 19,
      strength: 19,
      aggression: 18,
      determination: 17,
      pace: 14,
      jumping: 18,
      positioning: 15
    },
  },
];
